print("the information app:")
name=input("what is your name? : ")
clg=input('where is your clg? :')
principal=input('who is your principal:')
print('your details are:')
print('name',name)
print('clg',clg)
print('principal',principal)
confirm=input('is this ok?')
friend=input('who is ur frnd')
print('frnd')